### ISSUE TITLE
Ability to ignore certain domains?

### ISSUE THREAD

**Issue by privatemaker** [godbout/dash-docset-builder#25]
Hello. I was trying to create a docset for [HUGO](https://gohugo.io/) site generatorusing your tool. It seemed to be working fine, but take a bit of time... upon looking I realized it was downloading entire the [discourse.gohugo.io](https://discourse.gohugo.io) forum, which is linked in the topbar.

Would you consider adding a config value such as:

```
public const IGNORE_DOMAINS = [
    'discourse.gohugo.io',
    'github.com',
    ...
];
```

**Comment by godbout** [comment]
you should be able to already. wait.

**Comment by godbout** [comment]
you can actually override the grab method and do whatever you want. see https://github.com/godbout/dash-docset-builder#edit-your-pretty-docset-class the second part with `wget` and the `reject-regex` etc.

you can see live from the examples given in the README: https://github.com/godbout/dash-docset-builder#docsets-generated-with-this-builder

e.g.:  https://github.com/godbout/tailwindcss-dash-docset/blob/master/app/Docsets/TailwindCSS.php

have fun
