### ISSUE TITLE
Composer Error. Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by sheriffyusuf** [godbout/dash-docset-builder#9]
Problem 1
    - Root composer.json requires godbout/dash-docset-builder ^1.2 -> satisfiable by godbout/dash-docset-builder[1.2.0].
    - godbout/dash-docset-builder 1.2.0 requires wa72/htmlpagedom dev-master -> found wa72/htmlpagedom[dev-master, 2.0.x-dev (alias of dev-master)] but it does not match your minimum-stability.

**Comment by godbout** [comment]
oops. i might have misunderstood how the VCS option `composer` works. strangely all the tests went green though. thanks for reporting. will investigate ASAP.

**Comment by sheriffyusuf** [comment]
Thank you for this awesome tool.

**Comment by godbout** [comment]
welcome.

i have something working but i'm gonna spend a bit more time trying to understand completely what's happening. patch release should happen in about 6 hours.

**Comment by godbout** [comment]
ok, so it seems that what i'm trying to do is not possible.

if i get the `composer` docs correctly, you can't require packages that are not on `Packagist` without first writing a root `composer.json`. see:
* https://getcomposer.org/doc/05-repositories.md#repository
* https://getcomposer.org/doc/faqs/why-can't-composer-load-repositories-recursively.md
* https://getcomposer.org/doc/04-schema.md#root-package

that means there's a few ways to solve this:

1. get wasinger to merge a PR: https://github.com/wasinger/htmlpagedom/issues/35 (not controllable)
2. me pushing my htmlpagedom fork on Packagist (controllable)
3. ask `dash-docset-builder` users to paste a `composer.json` before running the command (sucks)
4. releasing the tool through `homebrew`? (not sure PHP version constraints can be required tho)

seems point 2 is the most straightforward, but i'd like to avoid polluting `Packagist` if possible. i'm not planning to "maintain" `htmlpagedom`, i'm just making it compatible with PHP8.0.

any thoughts?

if you don't need PHP8.0 support, you can install the previous minor version like this:

`composer require godbout/dash-docset-builder:"~1.1.0"`

**Comment by godbout** [comment]
should be working now.

usually i bump the minor version of a package when i drop support for a PHP version, but in this case it's better to bump the major version (explanation [here](https://github.com/godbout/dash-docset-builder/releases/tag/2.0.0)). so now `composer require godbout/dash-docset-builder` will install `^2.0`, that supports the two current active PHP versions (8.0, and 7.4). if you have a lower PHP version, please use and specify version 1 with `composer require godbout/dash-docset-builder:^1`.

let me know if you issue is solved. thanks.

**Comment by godbout** [comment]
i'll try to add tests to check the installation result (https://github.com/godbout/dash-docset-builder/issues/11).

**Comment by sheriffyusuf** [comment]
> ok, so it seems that what i'm trying to do is not possible.
> 
> if i get the `composer` docs correctly, you can't require packages that are not on `Packagist` without first writing a root `composer.json`. see:
> * https://getcomposer.org/doc/05-repositories.md#repository
> * https://getcomposer.org/doc/faqs/why-can't-composer-load-repositories-recursively.md
> * https://getcomposer.org/doc/04-schema.md#root-package
> 
> that means there's a few ways to solve this:
> 
> 1. get wasinger to merge a PR: https://github.com/wasinger/htmlpagedom/issues/35 (not controllable)
> 2. me pushing my htmlpagedom fork on Packagist (controllable)
> 3. ask `dash-docset-builder` users to paste a `composer.json` before running the command (sucks)
> 4. releasing the tool through `homebrew`? (not sure PHP version constraints can be required tho)
> 
> seems point 2 is the most straightforward, but i'd like to avoid polluting `Packagist` if possible. i'm not planning to "maintain" `htmlpagedom`, i'm just making it compatible with PHP8.0.
> 
> any thoughts?
> 
> if you don't need PHP8.0 support, you can install the previous minor version like this:
> 
> `composer require godbout/dash-docset-builder:"~1.1.0"`

This explains a lot. Thanks. But I dont have any suggestions

**Comment by sheriffyusuf** [comment]
> should be working now.
> 
> usually i bump the minor version of a package when i drop support for a PHP version, but in this case it's better to bump the major version (explanation [here](https://github.com/godbout/dash-docset-builder/releases/tag/2.0.0)). so now `composer require godbout/dash-docset-builder` will install `^2.0`, that supports the two current active PHP versions (8.0, and 7.4). if you have a lower PHP version, please use and specify version 1 with `composer require godbout/dash-docset-builder:^1`.
> 
> let me know if you issue is solved. thanks.

Am yet to try it. But I will do so and give feedback ASAP.

**Comment by sheriffyusuf** [comment]
Alright. I have tried it out. It installs without any issues. Thank you.
